### ISSUE TITLE
Unable to load other languages with CascLib from OverTool

### ISSUE THREAD

**Issue by xyx0826** [overtools/OWLib#10]
I was using the OverTool version of CascLib with CascExplorer to browse game files. However with the latest Explorer and Lib (OverTool branch, not vanilla), I was unable to read languages other than enUS in Explorer - no matter what locale I selected, the actual files and APMs in TactManifest were all from enUS.

**Comment by Js41637** [comment]
If you're using the latest, are you doing `-L=enUS` ?

**Comment by naomichan** [comment]
I'll look into it.

**Comment by naomichan** [comment]
Fixed in the CASCExplorer fork: https://ci.appveyor.com/api/buildjobs/9e8crw6fomrnnt3o/artifacts/CASCExplorer%2FCASCExplorer%2Fbin%2FCASCExplorer.zip
