### ISSUE TITLE
Enable Nullable annotations for TankLib and DataTool

### ISSUE THREAD

**Issue by yretenai** [overtools/OWLib#117]
This should help in finding bugs relating to null reference exceptions.

**Comment by Js41637** [comment]
![795026607663743044](https://user-images.githubusercontent.com/6258213/115142161-98d22180-a083-11eb-8088-0aca01839678.gif)

**Comment by prophetl33t** [comment]
bruh

**Comment by Js41637** [comment]
![795026607663743044](https://user-images.githubusercontent.com/6258213/115142161-98d22180-a083-11eb-8088-0aca01839678.gif)

**Comment by prophetl33t** [comment]
News that a team is taking longer than anticipated with nullable annotations for TankLib and DataTool
is never easy, especially in a case where users have been eagerly anticipating any information about release, beta, etc. The forums, reddit, and social have all been a reflection of the frustration I believe a lot of overtools users are feeling today, and that’s ok.

I have been spending the last day gathering feedback, and today I’ll be summarizing it and sending it along to the those who need to see it. While it’s important that our team does everything in our power to meet the high expectations that we all have for the overtools franchise, we also need to be aware of how it affects the community that’s grown up around our tools.

In the meantime, I want you all to know that we understand what’s happening in social media. While we still believe that this is the right thing to do for the team, the OWLib, and ultimately the users, we get the emotions being shared today.

One rumor to clear up: I’m seeing a lot of folks assuming a launch date in 2069 is wrote. Without being pedantic, I want to point out that there was no release date or beta date communicated in yesterday’s earnings call (were making millions of bucks from OSS btw). While I’m not prepared to discuss dates with you here today, I want to quash the rumor of a Overwatch 3 release date as being somehow “official”.

To the OP: I understand where you’re coming from and sincerely hope to have the opportunity to restore your feelings of excitement and joy about overtools and the team behind it.
