### ISSUE TITLE
OverTool not working? 

### ISSUE THREAD

**Issue by theoneandonlyjustin** [overtools/OWLib#12]
Here's the command I used: 
`overtool C:\Program Files (x86)\Overwatch m` 
but when I hit enter, I get a list of command args and not a list of maps. How does this work? Here's a screenshot of my files: 
![capture](https://user-images.githubusercontent.com/22670587/28224465-34ad8d42-689d-11e7-822a-8e8365cdd138.PNG). Is there something I'm missing or is it something to do with my files/directory? Do I have to install OverTool in the Overwatch directory>

**Comment by nebularg** [comment]
you need to quote paths with spaces

**Comment by theoneandonlyjustin** [comment]
Thanks!

**Comment by theoneandonlyjustin** [comment]
Thanks!
