### ISSUE TITLE
CMF procedure is outdated?

### ISSUE THREAD

**Issue by theoneandonlyjustin** [overtools/OWLib#13]
Source command: `overtool "C:\Program Files (x86)\Overwatch" m`
Output: ```OverTool v1.12.0.24-git-59e1a613d49335042db3aff6bf77ea1726e7a5ce
Initializing CASC...
Set language to enUS
Using Overwatch Version 1.12.0.2.38058
CASC CDN Cache path is C:\Users\jungh\Downloads\OverTool\files\CascCache
Loading APM TactManifest/Win_SPWin_RDEV_LenUS_EExt.apm
No CMF procedure for build 38058, trying closest version
Using CMF procedure 37793
CMF Procedure is outdated, cannot parse TactManifest/Win_SPWin_RDEV_LenUS_EExt.apm```
What do I have to update?

**Comment by nebularg** [comment]
You need to update CASCExplorer (OWLib uses ea1cfb4). Go into the folder, checkout overwatch, and pull

**Comment by nebularg** [comment]
Also since I _just_ went through this, you'll probably have to fix Util.OpenFile (APMFile.Packages ends up null for whatever reason)
```diff
diff --git a/OverTool/Util.cs b/OverTool/Util.cs
index 2ddeed7..beb9f0e 100644
--- a/OverTool/Util.cs
+++ b/OverTool/Util.cs
@@ -72,7 +72,7 @@ namespace OverTool {
                 if (recur) {
                     OwRootHandler ow = (OwRootHandler)handler.Root;
                     foreach (APMFile apm in ow.APMFiles) {
-                        if (!apm.Name.ToLowerInvariant().Contains("rdev")) {
+                        if (!apm.Name.ToLowerInvariant().Contains("rdev") || apm.Packages == null) {
                             continue; // skip
                         }
                         for (int i = 0; i < apm.Packages.Length; ++i) {
```

**Comment by theoneandonlyjustin** [comment]
You need to update CASCExplorer (OWLib uses ea1cfb4). Go into the folder, checkout overwatch, and pull

What does theat mean: "checkout overwatch and pull"?

**Comment by theoneandonlyjustin** [comment]
Can I get a response to my above question?

**Comment by naomichan** [comment]
Update CascLib.dll from here https://ci.appveyor.com/project/yukimono/owlib/build/artifacts

**Comment by nebularg** [comment]
@theoneandonlyjustin New to git? CASCExplorer is a submodule meaning that folder is its own git repo and in this case pointed at a specific commit. To get the latest I suggested to go into that repo, check out it's main branch (overwatch), then pull to fetch updates. 

As for the file path, it's listed at the top of the diff.

**Comment by theoneandonlyjustin** [comment]
@nebularg Yeah, new to GitHub is right. Thanks!
