### ISSUE TITLE
[Question] Decryption keys

### ISSUE THREAD

**Issue by SuzukazeSotaro** [overtools/OWLib#138]
Hello,

I wondered how you manage to get the decryption keys for each new version of overwatch ? [TankLib/Overwatch.keyring](https://github.com/overtools/OWLib/blob/master/TankLib/Overwatch.keyring) / [TACTLib/Core/Product/Tank/CMF/ProCMF_82693.cs](https://github.com/overtools/TACTLib/blob/master/TACTLib/Core/Product/Tank/CMF/ProCMF_82693.cs)

**Comment by ZingBallyhoo** [comment]
We keep this stuff internal so blizzard doesn't get angry :)

**Comment by Js41637** [comment]
You can download a new update when we release one 😇
