### ISSUE TITLE
Constantly getting 'Error initializing CASC'

### ISSUE THREAD

**Issue by xProtoVI** [overtools/OWLib#151]
So just like what the title pretty much said which I have already tried the solution to scan and repair my game which didn't help at all so either I am missing something or I am clearly doing something wrong here.
![2021-10-17 (6)_LI](https://user-images.githubusercontent.com/68478816/137646355-918bd070-bf69-4940-9680-53f81360c707.jpg)

**Comment by xProtoVI** [comment]
> is F:\Overwatch definitely where your game is installed?

No, it's not I was just doing a command. My location for where Overwatch is at is C:\Program Files (x86)\Blizzard Games\Overwatch\_retail_\Overwatch.exe

**Comment by xProtoVI** [comment]
> use "C:\Program Files (x86)\Blizzard Games\Overwatch" (with quotation marks)
I don't really think it had anything to do with the pathing at all which I made sure it was at the correct location and I did try to do that with quotation marks which that didn't do anything for me.

**Comment by ZingBallyhoo** [comment]
post the error you are getting with the change I suggested. the error in the first screenshot is because you used the wrong path of `F:\Overwatch`

**Comment by yretenai** [comment]
for models

`DataTool "C:\Program Files (x86)\Blizzard Games\Overwatch" extract-unlocks D:\DataTool McCree`

for sounds

`DataTool "C:\Program Files (x86)\Blizzard Games\Overwatch" extract-hero-voice-better D:\DataTool McCree`

**Comment by Luke-L** [comment]
readme.txt 😂

**Comment by xProtoVI** [comment]
Okay thank you so much with the help and next time I should definitlity pay attention a little more. :)
