### ISSUE TITLE
Compatibility with Overwatch 2 Beta branch, ProB

### ISSUE THREAD

**Issue by x9** [overtools/OWLib#160]
**Is your feature request related to a problem? Please describe.**
This request is related to new functionality, not a problem.

**Describe the solution you'd like**
The Overwatch 2 Beta (ProB/prometheus_beta) client can be downloaded from Battle.net using third-party tools (https://github.com/barncastle/Battle.Net-Installer)

Is it possible for this tooling to be updated to allow for browsing/extraction of assets within the Beta client?

**Comment by Js41637** [comment]
It is unlikely that we will support the beta.

If we support the beta most people are just going to use it to leak stuff and we don't condone the use of our tools for leaking.

**Comment by yretenai** [comment]
Closing as we will not support other branches, and the beta has ended anyway.
