### ISSUE TITLE
I was interested in finding the health / damage / cooldown timers and abilities. 

### ISSUE THREAD

**Issue by pjmagee** [overtools/OWLib#161]
Would the hero likely also contain that data or would this be something in another file that isnt reverse engineered yet?

https://github.com/overtools/OWLib/blob/afffab8447d7dd0fb41a97f5868876f381a5e6d4/DataTool/DataModels/Hero/Hero.cs#L12

I ran the Viewer locally, its really nice.

**Comment by Js41637** [comment]
Unfortunately this data is not easy to find, this data is mostly contained inside Statescript Graphs which are very challenging to parse and understand.

**Comment by prophetl33t** [comment]
I tried to implement ability/weapon stats finder in #129, but I couldn't make it work consistently primarily because of the reason Js pointed out above.
