### ISSUE TITLE
Discord invitation link

### ISSUE THREAD

**Issue by Hadditor** [overtools/OWLib#173]
Heya, just wondering if the Discord link can be fixed please

**Comment by ZingBallyhoo** [comment]
Can you clarify? It works fine for me

![image](https://github.com/overtools/OWLib/assets/13888932/b826dc33-5061-4455-9666-de177d1d87b6)

**Comment by Hadditor** [comment]
Strange, I'm just clicking the link in the project description

![image](https://github.com/overtools/OWLib/assets/48568664/98f415e3-0ab7-488d-b78f-da6674f2ca61)

**Comment by Hadditor** [comment]
Alright, the link from git doesn't work in the browser - but pasting the "XM93ZdB" into the Discord app directly does join the server, so just a Discord issue

Thanks

**Comment by OldDesigner** [comment]
![image](https://github.com/user-attachments/assets/f2f53167-a3f6-4702-b1b8-146f8bd971ce)
I can't even with the "XM93ZdB" code
