### ISSUE TITLE
STUD Instances length zero array with map extraction

### ISSUE THREAD

**Issue by ThatRubenAguilar** [overtools/OWLib#27]
When extracting a map overtool crashes on index out of bounds exception.

ExtractMap assumes length [here](https://github.com/overtools/OWLib/blob/overwatch/1.14/OverTool/Extract/ExtractMap.cs#L114), but STUD constructs with zero length arrays in [certain conditions.](https://github.com/overtools/OWLib/blob/overwatch/1.14/OWLib/STUD.cs#L54)

I have a couple questions to make sure this isn't a fake issue:

I am using the `overwatch/1.14` branch, is this considered a stable branch?

Are there any other errors I should look for that would cause the stud header magic to be improperly read?

Console Output:
```
D:\Code> D:\Code\GitHub\OWLib\dist\Debug\OverTool.exe "D:\Games\Blizzard\Overwatch 1.14.1.2.39484" map "D:\Resources\Overwatch Resourc
es\Maps" "Hanamura"
CASC CDN Cache path is D:\Code\GitHub\OWLib\dist\Debug\CascCache
OverTool v1.13.0.0-git-unknown
Initializing CASC...
Set language to enUS
Using Overwatch Version 1.14.1.2.39484
Loading APM TactManifest/Win_SPWin_RDEV_LenUS_EExt.apm
Using CMF procedure 39484
Loading APM TactManifest/Win_SPWin_speech_RDEV_LenUS_EExt.apm
Using CMF procedure 39484
Mapping...
Adding Encryption Keys...
Tooling...

Unhandled Exception: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at OverTool.ExtractMap.Parse(Dictionary`2 track, Dictionary`2 map, CASCHandler handler, Boolean quiet, OverToolFlags flags) in D:\Code\GitHub\OWLib\OverTool\Extract\ExtractMap.cs:line 114
   at OverTool.Program.Main(String[] args) in D:\Code\GitHub\OWLib\OverTool\Program.cs:line 168
```

**Comment by naomichan** [comment]
Overtool DOES NOT work with 1.14, it will _never_ work with 1.14.

DataTool is the only tool supporting 1.14 at the moment, and that has no export functionality as of yet.

overwatch/1.14 is incomplete.
