### ISSUE TITLE
CMF Procedure outdated, cannot parse

### ISSUE THREAD

**Issue by astatinium** [overtools/OWLib#28]
Hello,

I wanted to extract the newest Mercy voice lines that are only available at the PTR so i downloaded the latest version of the OverTool and i wrote this command:

`overtool -L=ptBR "C:\Program Files (x86)\Overwatch Test" V "C:\Users\astatinium\Downloads\OverMercy" Mercy`

The messages i get when running this command are the following:

`CASC CDN Cache path is: C:\Users\astatinium\Downloads\toolchain-release\CascCache
OverTool v.1.14.0.155-git-894232bed699a3696754cad5953d5d83baedafd6
Initializing CASC...
Set language to ptBR
Using Overwatch Version 1.15.0.0.39612
Loading APM TactManifest/Win_SPWin_RDEV_LptBR_EExt.apm
No CMF procedure for build 39612, trying closest version
Using CMF procedure 39484
CMF Procedure is outdated, cannot parse TactManifest/Win_SPWin_RDEV_LptBR_EExt.apm
`

I came here after i followed what was here:
https://github.com/overtools/OWLib/issues/13

but it didn't work.

What should I do?

**Comment by ZingBallyhoo** [comment]
@astatinium OverTool no longer supports the PTR, and voice line extraction hasn't been working since 1.14.

Which voice line is it, I might have a copy of it.

**Comment by astatinium** [comment]
@ZingBallyhoo I wanted the one ones from the new Valkyria ultimate, rez and the new "Hello!" but i wanted the ptBR version.

**Comment by ZingBallyhoo** [comment]
@astatinium 

Here are all the ones I could find:
https://clyp.it/gbxk2a0q
https://clyp.it/5xxduanm
https://clyp.it/u0qh2hbr
https://clyp.it/s5dvjv2x
https://clyp.it/q5xtithq
https://clyp.it/emgz1m03
https://clyp.it/snfxmsve
https://clyp.it/usomzsqq
https://clyp.it/dnzumhhb
https://clyp.it/pe0r5lym
https://clyp.it/nwfrqsah
https://clyp.it/2afoxf2c
https://clyp.it/mfu34rib
https://clyp.it/cfhhsev0

**Comment by astatinium** [comment]
@ZingBallyhoo Thanks, but i wanted in ptBR and those are in English. Thanks anyway. But you know how can i get them?

**Comment by Js41637** [comment]
PTR builds of Overtool are no longer supported. When the update is released live an Overtool (DataTool/CMF) update should be available.

**Comment by ZingBallyhoo** [comment]
@astatinium Oh, right. Unfortunately you're going to have to wait until 1.15 goes live, all of those files are from the past and I didn't have that language installed, sorry.

**Comment by Js41637** [comment]
Also as mentioned that 1.14 and 1.15 require DataTool now right? DataTool does not support extracting anything yet.

**Comment by astatinium** [comment]
Ok so i tried again with the latest version of OverTool and things were going fine so no longer outdated but now i get another issue:

![image](https://user-images.githubusercontent.com/29357305/30698375-ab262f7a-9ed9-11e7-80e3-5b07c669bac4.png)

You guys know what this could be?
