### ISSUE TITLE
Otool output?

### ISSUE THREAD

**Issue by theoneandonlyjustin** [overtools/OWLib#29]
Where does everything go? I used this command: ```overtool "C:\Program Files (x86)\Overwatch" g``` and got 
```CASC CDN Cache path is C:\Users\jungh\Documents\otool\CascCache
OverTool v1.13.2.0-git-5b95e70585d5c320fa409c361e26439585a64ee9
Initializing CASC...
Set language to enUS
Using Overwatch Version 1.14.1.2.39484
Loading APM TactManifest/Win_SPWin_RDEV_LenUS_EExt.apm
Loading APM TactManifest/Win_SPWin_speech_RDEV_LenUS_EExt.apm
Mapping...
Adding Encryption Keys...
Tooling...
```
Where does it go? the output folder is empty.

**Comment by Js41637** [comment]
Overtool does not work on Overwatch 1.14. `g` option only lists General Items. It has no output.

**Comment by naomichan** [comment]
OverTool is getting replaced with DataTool over the next few months for Overwatch 1.14 ongoing, but it's still an unfinished piece of software. Sorry.

**Comment by theoneandonlyjustin** [comment]
Where is DataTool?

**Comment by ZingBallyhoo** [comment]
@theoneandonlyjustin Right here in this repo. Remember that **it is not ready yet**

https://github.com/overtools/OWLib/tree/overwatch/1.14/DataTool
