### ISSUE TITLE
OverTool unhandled exception: Index was outside the bounds of the array.

### ISSUE THREAD

**Issue by astatinium** [overtools/OWLib#30]
Ok so i tried again to extract the new Mercy voice lines with the latest version of OverTool and things were going fine so no longer outdated and that but now i get another issue:

![image](https://user-images.githubusercontent.com/29357305/30698375-ab262f7a-9ed9-11e7-80e3-5b07c669bac4.png)

You guys know what this could be? 

What i typed was:

`overtool -L=ptBR "C:\Program Files (x86)\Overwatch" V "C:\Users\astatinium\Downloads\OverMercy" Mercy`

**Comment by ZingBallyhoo** [comment]
@astatinium Overtool is broken because the STU file format was changed in 1.14 and we haven't recovered yet. 

The new tool you will need to use is DataTool, but there is no mode for extracting voicelines yet. I'll get on it soon.
