### ISSUE TITLE
1.16 directly convert wem to ogg, how to make it not to convert

### ISSUE THREAD

**Issue by kaikaiiiiiii** [overtools/OWLib#38]
We have dictated many lines of English and Chinese into text., but we used md5 as the file's index and to check which are the same file after version's change.

Overtool is very good, but it use it's own file name system.

![](http://kaikai.info/wp-content/uploads/2016/10/Untitled-1.png)

In the old version of overtools I can still get the original wem format file. With original wem file I can still use tools to calculate the md5 and keep checking out the same file, and keep the dictation continued.

![](http://kaikai.info/wp-content/uploads/2016/10/tagmatching.png)

But today I tried 1.16 of the new DataTool, I found that it will automaticly convert wem into ogg, which makes it impossible to check which files are newly added, while which files are the same as old and already be dictated.

So what I really want to ask is to get the md5 value of every sound or pic file. Or at least a option not to convert wem to ogg then I can calculate md5 myself. We've already dictated about 20k lines of voice, don't want them be wasted.

**Comment by ZingBallyhoo** [comment]
To not convert sound, add `--convert-wem=false` to the command

To not convert textures add `--convert-textures=false`

**Comment by ZingBallyhoo** [comment]
slight update, the newest version of DataTool uses `--convert-sound` instead of `--convert-wem`
