### ISSUE TITLE
v1.22.0.541 bug: it can extract subtitles but don't extract some same-name sound files.

### ISSUE THREAD

**Issue by kaikaiiiiiii** [overtools/OWLib#46]
for example, the line:

00000004A5C4.0B2 | If you're not coming soon, you may as well   turn around.

you can find the line by using extract-subtitles-real, but can't find the same name sound file. I extract every part of the client, including maps, heros, herovoice or others. 

The full list that can't extract sound file but exists in subtitles-real:

00000004C3C3.0B2 | We're at the extraction point, where are   you?
00000004A5C4.0B2 | If you're not coming soon, you may as well turn around.
000000049B54.0B2 | Our ride is on its way. We need to stay alive until it gets here.
00000004C3D8.0B2 | Someone start breaching the door!
00000004A5B8.0B2 | Anyone going to start the breach? Or should we get Genji to cut a hole in   the door?
00000004A5B3.0B2 | You complaining isn't going to solve anything.
00000004A59C.0B2 | Someone get started on the door! (sigh) Do I have to do everything   myself?
00000004C3E1.0B2 | He didn't take them up on their offer?
00000004A5AE.0B2 | Fine. No ill effects so far.
00000004A580.0B2 | It wasn't how I drew it up.
00000004A581.0B2 | Yeah, they've really rolled out the red carpet.
00000004C3D1.0B2 | I still think we should have gone with the original plan of disguising   ourselves as the band.
00000004C3E5.0B2 | Not well.
00000004A57E.0B2 | And getting shot at.
00000004A57F.0B2 | No problem, we're used to waiting around.
00000004C3CA.0B2 | You call this art? A child could have made it.
00000004A5CC.0B2 | Enough art, let's get out of here.
00000004A5CB.0B2 | Extraction point's in sight.
00000004C3C4.0B2 | We need pickup now!
00000004C3CF.0B2 | Looks like I was wrong.
00000004A59D.0B2 | I thought you had the stomach for it.
00000004A59E.0B2 | Blackwatch has always had one purpose: to do the real work of keeping the   world safe.
00000004A5AF.0B2 | Trust me, Jesse. You should know by now, I won't lead you wrong.
00000004A5A6.0B2 | Always have.
00000004C3E8.0B2 | You know your brother would have made a good agent.
00000004C3DF.0B2 | I'm never going to hear the end of this, am I?
00000004C3D6.0B2 | Touchy subject.
00000004C3CC.0B2 | Good. Because I'm going to need you, Jesse.
00000004C3C7.0B2 | I don't need the statues and the medals anyway.
00000004A5BE.0B2 | Flexibility is the sign of an evolved mind.
00000004A5BF.0B2 | Not a second too soon.
000000049B9E.0B2 | Our ride's here! Get ready to move out!
00000004A5C1.0B2 | There's the one who will probably take over for him... Vialli. Don't know   too much about him.
00000004A5C2.0B2 | And an omnic who runs a casino in Monaco... Maximilien or something.
00000004A5C3.0B2 | Then Doomfist in Numbani.
00000004A5AC.0B2 | Why is this taking so long?
00000004A5AA.0B2 | Twenty years and we still can't get a door open?
00000004A5AB.0B2 | We have to make these damn things work faster.
000000049B8E.0B2 | We're making progress on the door. How's everyone doing?
00000004A5B0.0B2 | He's an arms dealer with some other interests, more and less legitimate.
000000049BD9.0B2 | We get out of this room then head through the city to the extraction   point.
00000004A59B.0B2 | Hear that? The ninja agrees with my decision.
00000004A5A3.0B2 | After that, we sit tight and hope someone comes to pick us up.
00000004A5A5.0B2 | You let me worry about what Jack needs to know.
00000004A5A4.0B2 | No, but I could shoot you.
00000004C3E6.0B2 | This mess was all worth it to see McCree trying to pass himself off as a   waiter.
00000004C3DC.0B2 | Didn't think that would be your scene.
00000004C3CD.0B2 | You got fired from your cover job, Jesse.
00000004A59F.0B2 | He thought he was untouchable. He was mistaken.
00000004A5A0.0B2 | (laughs) That's not going to happen.
00000004A5A1.0B2 | I made a decision, I'll deal with the consequences.
00000004A5B6.0B2 | There's that famous McCree attitude.
00000004A5B7.0B2 | Jesse, get that door open.
00000004C3CB.0B2 | Someone start breaching the front door.
00000004A5B5.0B2 | We need to find a way out of this room.
00000004A648.0B2 | We need to get out of here before the whole base is on top of us.
000000049B4D.0B2 | Now he's not our problem any more.
000000049B86.0B2 | Antonio was right, there's nothing we could do to him.
00000004A5B4.0B2 | Looks like they've got this place sealed tight.
00000004A5B2.0B2 | Someone start a breach on the front door.
00000004C3C8.0B2 | Point taken.
00000004A583.0B2 | Art gallery's in sight, we'll be there shortly.
000000049B41.0B2 | The art gallery's not far. Our extraction point's just past it.
00000004C3E3.0B2 | What's your status, pilot?
00000004C3D0.0B2 | We're all fine here, how are you?
00000004C3C9.0B2 | Where's the fun in that?
00000004C3E4.0B2 | Fly casual.
00000004A592.0B2 | Maintain operational silence, McCree.
00000004A593.0B2 | And I thought Reinhardt could throw a punch.
00000004A594.0B2 | Feels like Talon is mobilizing an entire army to stop us.
00000004A5CA.0B2 | Shut up and keep shooting!
00000004A5BD.0B2 | Get on board or we're leaving you behind!
00000004A582.0B2 | It's not exactly carnival.
000000049BA0.0B2 | Let's just get out of here alive.
000000049B3D.0B2 | At least someone is on my side.
00000004C3D5.0B2 | I never have and I don't intend to start now.
00000004C3E0.0B2 | Someone has to be the one to get things done.
00000004C3DE.0B2 | I was looking forward to the masquerade.
00000004A59A.0B2 | Agents down! Need immediate evac!
00000004A591.0B2 | That thing's bigger than Reinhardt!
00000004A590.0B2 | I withdraw my previous comment.
00000004A58F.0B2 | We're definitely not out of the woods yet.
00000004A58A.0B2 | Keep moving and don't let that sniper get a bead on you!
00000004A57C.0B2 | Don't let her get close.
000000049B47.0B2 | Let's get out of here.
000000049BBB.0B2 | What's keeping our ride? We can't wait forever.
000000049B6F.0B2 | Breaching now! Get ready!
000000049B7A.0B2 | Everyone, through the breach. We're getting out of here!
000000049BE5.0B2 | Breach in progress. Everyone get settled in.
00000004A5C0.0B2 | If you want something done right...
00000004A5B9.0B2 | This is it! Don't do anything stupid!
00000004A585.0B2 | It should be smooth sailing from here.
00000004A5A7.0B2 | Who knows where this goes.
00000004A5A8.0B2 | Not this way.
00000004A5A9.0B2 | No way out over here.
00000004C3DD.0B2 | Everyone, get ready to get on board.
00000004C3C5.0B2 | You heard her, let's move!
00000004C3E7.0B2 | Am I the only one who feels hungry?
00000004C3D7.0B2 | No reservation. Party of four. Bit of a last minute thing.
00000004C3C6.0B2 | I was making a joke.
00000004C3D2.0B2 | Jesse.
00000004C3D9.0B2 | We made it to the art gallery, but I don't see you.

**Comment by ZingBallyhoo** [comment]
Not a bug.

Reyes' Retribution sounds are defined somewhere else.

**Comment by kaikaiiiiiii** [comment]
@ZingBallyhoo  Can I ask how to extract these sounds? Where's the "somewhere else"?

I mean, since the extract-subtitles-real command can find these text, I guess the datatool already find these sound files's position in CASC cabs. But I've already tried all of extract-* commands, can't really find any of sound file listed above.

Or it did, can't be extracted yet?

Thank you for reply.

**Comment by ZingBallyhoo** [comment]
Can't be extracted with any DataTool modes right now.

For the moment you can use CASCExplorer to get whatever you need.

**Comment by kaikaiiiiiii** [comment]
@ZingBallyhoo Thank you, I'll try.
