### ISSUE TITLE
Music extraction?

### ISSUE THREAD

**Issue by Zekfad** [overtools/OWLib#47]
For now DataTool can only extract only characters' voicelines.
I'd want to know if there's plans for announcer's/game music extraction?

**Comment by healingbrew** [comment]
I'll look into it.

**Comment by UniqueUname** [comment]
I don't know if this is still relevant but, it'd be a nice to see this feature now that sigma got added.
We could use official sigma's theme music

**Comment by TheEvilSocks** [comment]
> 
> 
> I don't know if this is still relevant but, it'd be a nice to see this feature now that sigma got added.
> We could use official sigma's theme music

Sigma's tune is present in the `Title Screen:BED` map

**Comment by Zekfad** [comment]
@UniqueUname you still can use TankView to extract any sound present in a game, but its kinda hard, because you don't know exactly which file you needs and there's a ton of it.

**Comment by UniqueUname** [comment]
I know, I looked around 200~ files and all I got was anniversary theme and map loading tracks

**Comment by Js41637** [comment]
Yeah sorry guys, i wouldn't hold out hope of a music extraction command anytime soon.

**Comment by UniqueUname** [comment]
> > I don't know if this is still relevant but, it'd be a nice to see this feature now that sigma got added.
> > We could use official sigma's theme music
> 
> Sigma's tune is present in the `Title Screen:BED` map

Thanks for replying but DataTool doesn't seem to extract any sound from it.

**Comment by Js41637** [comment]
There is now a `extract-music` command which extracts some of the music in the game. Better than nothing.
