### ISSUE TITLE
Extract Announce SFX

### ISSUE THREAD

**Issue by naomichan** [overtools/OWLib#5]
Ability to extract announcer SFX

Ref: https://owdev.wiki/Sound_Files/Voices#Athena

**Comment by Js41637** [comment]
Do you want me to provide a list of all the fileIDs i've found for Athena?

**Comment by Js41637** [comment]
If you want some of the IDs for other voice files, I have basically everything from the `0B2` folder sorted into groups here https://overwatch-item-tracker.github.io/sounds/

I compared everything exported from 0B2 with what Overtool lists and viewed the difference which is roughly 1500 files that Overtools `v` doesn't export though about 400 of these are Skin Voicelines which I don't know if the skin option exports?

Anyway, the remaining files are Junkenstein, Snowball Offensive, Uprising and Lucioball commentator sounds. Athena and the hollywood guy and a bunch of misc sounds.
