### ISSUE TITLE
StackOverflowException when extract Junkenstein on 1.29

### ISSUE THREAD

**Issue by kaikaiiiiiii** [overtools/OWLib#51]
cmd line:
`tools\DataTool.exe -L=enUS -T=enUS --graceful-exit --ex "..\Overwatch" --convert-sound=false --convert-lossless-textures=true --skip-models=true --skip-animations=true extract-maps .\TCExtract1\en "Junkenstein's Revenge"`

result:
![cmd_2018-10-14_17-16-17](https://user-images.githubusercontent.com/1635138/46914809-1f9a7500-cfd5-11e8-9447-dee4d6e68302.png)

**Comment by ZingBallyhoo** [comment]
https://ci.appveyor.com/project/yukimono/owlib/builds/19500705
