### ISSUE TITLE
System.ArgumentNullException when extract-general things under zhCN language.

### ISSUE THREAD

**Issue by kaikaiiiiiii** [overtools/OWLib#52]
**command:** 

`tools\DataTool.exe -L=zhCN -T=zhCN "..\Overwatch" --convert-sound=false --convert-lossless-textures=true --skip-models=true --skip-animations=true extract-general .\TCExtract1\cn *`

**Screen Shot**
![cmd_2018-10-15_20-59-40](https://user-images.githubusercontent.com/1635138/46952386-3e743680-d0bd-11e8-9915-009d0df04b5e.png)

Some translation:
`System.ArgumentNullException: 值不能为 null`
= `System.ArgumentNullException: Value can't be  null`

`参数名：source`
= 'argument (or parameter) name: source`

`在` of every other lines' first character means "at".

**Error description:**
* always repeat.
* Appears in zhCN language. Not appears in enUS language. I'm not sure the bug will be or not be in other language.
* I tried to change extracting "all" (*) to "Spray" or "Other Unlocks" which can be found with list-* commands, bug still repeat.

**Version**
Datatool @ 1.29.0.787 (newest by now)
Overwatch @ 1.29.0.1.51948 (newest by now) with enUS / zhCN two languages.

**Comment by ZingBallyhoo** [comment]
thanks for the report once again.

should be fixed now (although untested)

https://ci.appveyor.com/project/yukimono/owlib/builds/19522221 (1.29.0.788)

**Comment by kaikaiiiiiii** [comment]
> thanks for the report once again.
> 
> should be fixed now (although untested)
> 
> https://ci.appveyor.com/project/yukimono/owlib/builds/19522221 (1.29.0.788)
> https://ci.appveyor.com/api/buildjobs/qcxo9ig39ijx1t0h/artifacts/dist%2Ftoolchain-release.zip

Tested. Bug fixed.
Thanks.
