### ISSUE TITLE
Can't extract Orisa skin

### ISSUE THREAD

**Issue by millionart** [overtools/OWLib#56]
**Describe the bug**
Can't extract Orisa skin

**To Reproduce**

`datatool "E:\Program Files (x86)\Overwatch" extract-unlocks "D:\OWmodels" "Orisa|skin=classic"`

**Logs**

> [Core] DataTool v1.31.0.797-git-be89b3e52d58b2a6f1987ce4764a9e80511ad5b4
> [Core] CommandLine: ["E:\Program Files (x86)\Overwatch", "extract-unlocks", "D:\OWmodels", "Orisa|skin=classic"]
> [Core] CommandLineFile: D:\Downloads\toolchain-release (2)\DataTool.exe.args
> [CASC] Overwatch build 1.32.0.1.54052
> [CASC] Initializing...
> [CMF] Using CMF procedure 54052
> [CMF] Using CMF procedure 54052
> [CASC] Ready
> [Core] Checking ResourceKeys
> [Core] Tooling...
> Processing unlocks for Orisa
>         Extracting skin Classic
>                 Finding
> System.ArgumentNullException: 值不能为 null。
> 参数名: input
>    在 System.IO.BinaryReader..ctor(Stream input, Encoding encoding, Boolean leaveOpen)
>    在 TankLib.teMaterial..ctor(Stream stream)
>    在 DataTool.FindLogic.Combo.Find(ComboInfo info, UInt64 guid, Dictionary`2 replacements, ComboContext context)
>    在 DataTool.FindLogic.Combo.Find(ComboInfo info, UInt64 guid, Dictionary`2 replacements, ComboContext context)
>    在 DataTool.FindLogic.Combo.Find(ComboInfo info, UInt64 guid, Dictionary`2 replacements, ComboContext context)
>    在 DataTool.FindLogic.Combo.Find(ComboInfo info, UInt64 guid, Dictionary`2 replacements, ComboContext context)
>    在 DataTool.SaveLogic.Unlock.SkinTheme.Save(ICLIFlags flags, String directory, STUSkinBase skin, STUHero hero)
>    在 DataTool.ToolLogic.Extract.ExtractHeroUnlocks.SaveUnlock(ICLIFlags flags, Unlock unlock, String path, String eventKey, Dictionary`2 config, Dictionary`2 tags, VoiceSet voiceSet, STUHero hero)
>    在 DataTool.ToolLogic.Extract.ExtractHeroUnlocks.SaveUnlocks(ICLIFlags flags, Unlock[] unlocks, String path, String eventKey, Dictionary`2 config, Dictionary`2 tags, VoiceSet voiceSet, STUHero hero)
>    在 DataTool.ToolLogic.Extract.ExtractHeroUnlocks.SaveUnlocksForHeroes(ICLIFlags flags, IEnumerable`1 heroes, String basePath, Boolean npc)
>    在 DataTool.ToolLogic.Extract.ExtractHeroUnlocks.Parse(ICLIFlags toolFlags)
>    在 DataTool.Program.Main()

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Overwatch Version 1.32.0.1
 - Overwatch Region China
 - Overwatch Language English

**Comment by Js41637** [comment]
This was posted on Facepunch, Reinhardt and Orisa both have issues extracting. Something about their data is abnormal.

**Comment by millionart** [comment]
Is this a game issue or a bug in this tool? Will this be fixed?

**Comment by Js41637** [comment]
Well its kinda both i mean, it didn't break due to changes we did. It is being looked into. No ETA when it will be fixed.

**Comment by healingbrew** [comment]
Most likely this weekend.

**Comment by healingbrew** [comment]
Should be fixed with the latest update. Please check.

**Comment by millionart** [comment]
Tested to extract Orisa Classic, works fine.
