### ISSUE TITLE
No CMF procedure for build 58625

### ISSUE THREAD

**Issue by millionart** [overtools/OWLib#59]
My client version is 1.36.0.1
I hope to support this version.

Thanks.

**Comment by Js41637** [comment]
I made a comment about this on Facepunch [here](https://forum.facepunch.com/dev/buoij/Overwatch-Model-Thread-v4/10/#postcxayrm)

I'll copy it here;

> Not sure if we will get around to making a release for the latest Overwatch version.
> 
> Updating the tools for new versions of the game takes time and is quite tedious.
> Only a handful of people are able to do it and we haven't been spending as much time working on Overwatch as of late.
> 
> So i'm not sure if we'll release an update for 1.36.0.1.58625 but we will definitely do the next major patch which should be next week.
> As we are spending less time on updating the tools I cannot stress enough the importance of keeping backups.
> You only need to keep at least 1 version of the game backed up that the tools support and the game isn't really that large.

**Comment by Js41637** [comment]
An update has been released.
