### ISSUE TITLE
Any way to exclude keys from being used?

### ISSUE THREAD

**Issue by Js41637** [overtools/OWLib#6]
Hey weird, question. I'm trying to just do some testing to see what content got added with what key except I can't seem to remove any keys. Removing all the keys from `ow.keys` only prevents Uprising data from being logged.
I also tried editing the keyService to remove the hard coded keys except everything still logs. Is it getting them from the server or am I missing something?

**Comment by naomichan** [comment]
1. Delete the majority of hard coded keys from KeyService
2. Delete the specified key from ow.keys
3. run

```
OverTool -n C:\Overwatch\ t...
OverTool -LenUS -n C:\Overwatch t...
OverTool -LenUS -n -q C:\Overwatch t...
```

The - arguments are order dependent.

**Comment by Js41637** [comment]
Yeah I just saw the `-n` in code. Still logs everything except Uprising though, no missing key errors.

**Comment by naomichan** [comment]
That's because CascLib now also loads keys from the keyring, I wrote some code that disables that if -n is present.

https://ci.appveyor.com/api/buildjobs/bcdljjlv8kirgaen/artifacts/dist%2Ftoolchain-release.zip

**Comment by Js41637** [comment]
Ah thank you, this works perfectly.
