### ISSUE TITLE
Failed to extract the map

### ISSUE THREAD

**Issue by millionart** [overtools/OWLib#60]
`Datatool "E:\Program Files (x86)\Overwatch" "D:\OWmodels" "Blizzard World"`

Show only
```
[Core] DataTool v1.36.0.818-git-8ebce40a849c4b7101b582f8e68a58bc640dc69a
[Core] CommandLine: ["E:\Program Files (x86)\Overwatch", "D:\OWmodels", "Blizzard World"]
[Core] CommandLineFile: D:\Downloads\toolchain-release (3)\DataTool.exe.args
```

Nothing happens after that

**Comment by ZingBallyhoo** [comment]
Correct syntax for extraction is `DataTool {overwatch directory} {extract mode} {output directory} {query}`

Use this: `Datatool "E:\Program Files (x86)\Overwatch" extract-maps "D:\OWmodels" "Blizzard World"`
