### ISSUE TITLE
Are there owanims for victory poses?

### ISSUE THREAD

**Issue by arcticmunkii** [overtools/OWLib#61]
Hi! Since the forum shut down, I can't really find much information about this anywhere. 

Are there any owanim files for victory poses? I'd like to be able to use victory poses with the guns in the correct position. Which is something I'm unsure of how to do. 

Any response would be much appreciated. 

Regards,

Tomas

**Comment by healingbrew** [comment]
Yes, they should be either in their individual folders, or in the entity folders.
