### ISSUE TITLE
Facepunch Forums closed - as same as Overwatch Model Threads

### ISSUE THREAD

**Issue by GraczCourier** [overtools/OWLib#62]
Tried to get the newest version to extract few models to create my hero's pistol - Chaser, but unfortunately Facepunch forums are closed, with Model Threads. 
What's going to happen now? Where should I go to ask for extracting?

I need this to create something based on it!

**Comment by Js41637** [comment]
There is a subreddit here, it also contains links to a discord that we use.

https://www.reddit.com/r/overtools/
