### ISSUE TITLE
"DataTool.exe" not opening

### ISSUE THREAD

**Issue by K3VRAL** [overtools/OWLib#64]
Every time I try to open the file, "DataTool.exe", it never wants to run, as in; it opens up the console, displays a few texts then closes immediately. I don't really know what to do as it keeps happening with other releases.

Windows 7 Ultimate is the version I am using

**Comment by TheEvilSocks** [comment]
Open CMD or Powershell and run it via that.

**Comment by ZingBallyhoo** [comment]
DataTool is a command line application.
