### ISSUE TITLE
Sigma can't be extracted

### ISSUE THREAD

**Issue by FifouBE** [overtools/OWLib#65]
It's impossible to extract sigma's unlock with the latest datatool "Patch 38 - Build 829"

The command : datatool "Overwatch directory" extract-unlocks "Output directory" "Sigma"

The CMD will give that output with nothing in the output folder:

```
[CASC] Overwatch build 1.38.0.3.60547
[CASC] Initializing...
[CMF] Using CMF procedure 60547
[CMF] Using CMF procedure 60547
[CASC] Ready
[Core] Checking ResourceKeys
[Core] Tooling...
[Core] Execution finished in 00:00:00.1775298 seconds
```

 - OS: Windows 10 latest
 - Overwatch build 1.38.0.3.60547

**Comment by PistonFX** [comment]
How can you extract something that's not live yet.

**Comment by FifouBE** [comment]
Omg, I play so much on PTR and see so many things about it that I think It's live lmao! My bad on this one
