### ISSUE TITLE
Animation ".seanim" files deforming models.

### ISSUE THREAD

**Issue by SausageTaste** [overtools/OWLib#67]
**Describe the bug**

* Since I watched a YouTube video that shows hidden Dva dance emote, I tried by myself to extract the animation with DataTool. I followed a tutorial [here](https://owdev.wiki/Tutorial/Import_animations_into_Blender) with "Using SEAnim Files" to get the [horrifying result](https://imgur.com/DLgPVNm).

**To Reproduce**

1. Download Datatool version 1.39.0.832, master branch of Blender addon, [io_scene_owm](https://github.com/overtools/io_scene_owm) as zip, [io_anim_seanim(v0.4.0)](https://github.com/SE2Dev/io_anim_seanim) as zip.
2. Run DataTool.exe like
> `DataTool.exe "{OW directory}" extract-unlocks "{output directory}" "D.Va|skin=Classic" --extract-refpose`
3. Find `000000001064.owmdl` file extracted and open in Blender installed addon.
4. As [tutorial](https://owdev.wiki/Tutorial/Import_animations_into_Blender) says, replace bones with `000000001064.smd` which seems like refpose. All looks good to this point, bones move body parts correctly.
5. With bones selected, import `000000006249.seanim` file which can be found in sub directory of model folder. Now the beast comes out.
6. Tried not replacing bones that is already within the model file, nope.

**Expected behavior**

* Baby DVa dancing.

**Logs**

* No error report from DataTool nor Blender.

**Environment**
 - Windows 10 with Korean system locale
 - Overwatch Version : 1.39.1.0.60993
 - Overwatch Region : Asia (If you need it)
 - Overwatch Language : English
- Blender 2.80

**Comment by ZingBallyhoo** [comment]
Something has changed with the seanim importer

**Comment by ZingBallyhoo** [comment]
this unofficial seanim works better for now, no idea what's different about it

https://cdn.discordapp.com/attachments/588235466214473739/608042023609434114/io_anim_seanim_test.zip

**Comment by ZingBallyhoo** [comment]
Actually, the correct fix is to use --scale-anims=false in `DataTool`. Don't know why the seanim devs changed the scale constant because now we have no idea how the importer is going to interpret the data

**Comment by SausageTaste** [comment]
Thanks that solved my problem. No doubt I couldn't find any problem myself because understanding animation file format is a whole new level thing. Then maybe `--scale-anims=false` be default in future builds? Again I appreciate your quick response!

**Comment by healingbrew** [comment]
Yes, next update will have it set to false by default.
