### ISSUE TITLE
Questions regarding sound files

### ISSUE THREAD

**Issue by Js41637** [overtools/OWLib#7]
Hey so i'm messing around with sounds trying to build a nice [viewer](https://overwatch-item-tracker.github.io/sounds/) for them as it's kinda hard to go through them at the moment and I'm just wondering about the process of extracting some of these sounds.

A recent change you made to the sound extractor was to group sets of sounds in sub folders (packages?) Going through them seems to mostly be:

- Weapons (Multiple Folders)
- Base sounds
- Event/New ? (Uprising and CTF voicelines)
- Weird default beeps

That's from McCree's although Widowmaker has 18 folders and a lot of them don't seem to be related to her? Some of these sound like some sort of jet engine and spraying sound and a bunch of single `.bnk` files.
Anyway so is there any way for me to identify these types of folders or what the sounds might be?
Something I have noticed is all non voice files seem to be a much higher number. All weapon sounds being `00000004....`

Also before when I was testing with removing keys for testing. So I was trying to get it to extract sound files for each key to get a diff of when sounds were added however it appears that this does not work. I figured that all the new sound files for events/keys would be linked however it seemed to export everything up to Uprising even without the keys (note that the event specific items still said missing key). Is it possible they removed the keys from the sound files? Also note Ana, Sombra & Orisa still have all their sounds tied to their keys.

So NPCs and sound files don't work very good at the moment. I understand it has something to do with how Overtool finds references to other files for a hero however in the case of NPCs which seem to be like shallow copies of heroes or making some reference to them that ends up extracting a lot of stuff not related to them. Most cases being Zenyatta as all the bots seem to reference him. The `Shock-Tire` NPC extracts over 900 sounds (Junkrat & Zenyatta) and it doesn't even have any actual sounds itself (that it has found).
I'm sure you're aware of the issue, you probably can't do anything about it I assume but I just figured I'd mention it.

Sorry if i'm annoying you with these questions.

**Comment by naomichan** [comment]
It creates folders for each "animation list" file.

The tool is very aggressive in how it finds sounds and animations, it will follow any link it can because I don't know exactly _how_ Overwatch loads the data correctly. This is with unrelated data files are being extracted.

**Comment by Js41637** [comment]
I know that the `x` skins export option also exports sound files now that skins use? Does the `v` option extract the same sounds? 
If you view the [link](https://overwatch-item-tracker.github.io/sounds/) I made in the other Issue about Athena, under `Unknown` sounds most of them are sounds from skins. Christmas skin sounds, Halloween Skin sounds, etc. I don't remember when going through the sounds exported from `v` but I don't think these sounds are included. Do you think you'd be able to find them if I give you some of their IDs?

**Comment by naomichan** [comment]
> I know that the x skins export option also exports sound files now that skins use?

Yes. Always has.

> Does the v option extract the same sounds?

No

> Do you think you'd be able to find them if I give you some of their IDs?

No, "v" was initially added as a debugging thing to see if sound extraction grabs a bunch of system sounds again. It's not currently possible to do a "v" output with item overrides. "x" will override them, though.

**Comment by Js41637** [comment]
Ok thanks. I will try and use the skin method to only exports sounds. I really don't want to sound like an ungrateful asshole but do you think there is some way to better extract all these sounds without extracting every referenced sound for every skin for every hero which results in like 233,000 sound files.

**Comment by naomichan** [comment]
Probably, but we just don't have the research into it.

**Comment by Js41637** [comment]
Sorry, not sure if you saw the edit

**Comment by naomichan** [comment]
Uh, maybe.

I can whip something up.

**Comment by naomichan** [comment]
new output mode "V" introduced in 45ae63e75ad1635f0889ead7a43e5e20587b67d0

It will extract base sounds, and then the replaced sounds for each skin.

**Comment by Js41637** [comment]
Omg you are amazing! You have to let me donate you some money or a steam game, blizzard gift card? for all the work you do!
