### ISSUE TITLE
TankView NGDP crash

### ISSUE THREAD

**Issue by Zekfad** [overtools/OWLib#71]
**Description**
TankView NGDP open option crashes the program. It's simply closes itself without any warning.

**To Reproduce**
1. Open TankView
2. Click on File
3. Click on Open...
3. Click on NGDP
4. Profit

**Expected behavior**
Dialogue of game folder choice.

**Desktop:**
 - OS: Windows 10 (OS Build 18362.356)

**Comment by ZingBallyhoo** [comment]
The NGDP option is for loading from Bnet servers. Use the file option instead.

**Comment by Zekfad** [comment]
Still isn't it supposed to work?

**Comment by Zekfad** [comment]
Ok, I got it, hope you will mark it as inactive or just remove form menu, next release.
