### ISSUE TITLE
Idle animations missing when extracting.

### ISSUE THREAD

**Issue by iceypotato** [overtools/OWLib#73]
When I extracted Mei, I couldn't find the idle animation that plays when she is in the overworld.
Here's: a youtube video to explain what I mean by idle animations: https://www.youtube.com/watch?v=TuX80xPluMg

**Comment by ZingBallyhoo** [comment]
there is a base pose, the rest are applied via additive animations which are not supported

**Comment by iceypotato** [comment]
So you mean this pose is incompatible?

**Comment by ZingBallyhoo** [comment]
its more than one pose layered on top of eachother, which is not supported

**Comment by iceypotato** [comment]
So it can't be extracted?

**Comment by ZingBallyhoo** [comment]
they all should be extracted, but if you try to import them individually it will just look like a blob on the floor

**Comment by iceypotato** [comment]
So, I can't just append the animations into Blender? Is there a way to solve this?

**Comment by ZingBallyhoo** [comment]
as i've said, no
