### ISSUE TITLE
Branch problem

### ISSUE THREAD

**Issue by rensole** [overtools/OWLib#74]
I tried extracting with both Quickdatatool and just through CMD.
Both give the same error and can't seem to extract anything anymore no matter what I try.

Datatool v1.42.0.855
Overwatch build 1.42.0.0.63869

I always get this:
Time now: 8-12-2019 19:16:32
Cmdline: DataTool.exe --language=enUS --cache --cache-data --convert-textures-type=tif "F:\hots\2\Overwatch" extract-unlocks ".\\" "|Skin="
Output: .\
[Core] DataTool v1.42.0.855-git-75497e17c0afb455b9aee19c9748faa43c08aa35
[Core] CommandLine: ["--language=enUS", "--cache", "--cache-data", "--convert-textures-type=tif", "F:\hots\2\Overwatch", "extract-unlocks", ".\", "|Skin="]
[Core] CommandLineFile: C:\Users\joost\Downloads\toolchain-release (4)\DataTool.exe.args
[CASC] Set language to enUS
[CASC] Overwatch build 1.42.0.0.63869
[CASC] Initializing...
[CMF] Using CMF procedure 63869
[CMF] Using CMF procedure 63869
[CASC] Ready
[Core] The branch "" is not supported!. This might result in failure to load. Proceed with caution.
[Core] Checking ResourceKeys
[Core] Tooling...
[Core] Execution finished in 00:00:00.7037186 seconds

**Comment by ZingBallyhoo** [comment]
agent db parsing should be fixed as of now
