### ISSUE TITLE
System.Exception: missing RIFF

### ISSUE THREAD

**Issue by DearVa** [overtools/OWLib#75]
This happens when I'm extracting maps.

F:\OWDataTool>datatool --language=zhCN E:\overwatch extract-maps E:\Overwatchoutput 釜山
[Core] DataTool v1.43.0.0-git-tanklib
[Core] CommandLine: ["--language=zhCN", "E:\overwatch", "extract-maps", "E:\Overwatchoutput", "釜山"]
[Core] CommandLineFile: F:\OWDataTool\DataTool.exe.args
[CASC] Set language to zhCN
[CASC] Overwatch build 1.43.0.0.64719
[CASC] Initializing...
[CMF] Using CMF procedure 64719
[CMF] Using CMF procedure 64719
[CASC] Ready
[Core] Reminder! When extracting data in other languages, the names of the heroes/skins/etc must be in the language you have chosen.
[Core] Checking ResourceKeys
[Core] Tooling...
Extracting map 釜山\7E2
        Finding
        Saving
System.Exception: missing RIFF
   在 DataTool.ConvertLogic.Sound.WwiseRIFFVorbis..ctor(Stream stream, String codebooksFile) 位置 F:\OWLib\DataTool\ConvertLogic\Sound.cs:行号 170
   在 DataTool.SaveLogic.Combo.ConvertSoundFile(Stream stream, Stream outputStream) 位置 F:\OWLib\DataTool\SaveLogic\Combo.cs:行号 702
System.Exception: missing RIFF
   在 DataTool.ConvertLogic.Sound.WwiseRIFFVorbis..ctor(Stream stream, String codebooksFile) 位置 F:\OWLib\DataTool\ConvertLogic\Sound.cs:行号 170
   在 DataTool.SaveLogic.Combo.ConvertSoundFile(Stream stream, Stream outputStream) 位置 F:\OWLib\DataTool\SaveLogic\Combo.cs:行号 702
System.Exception: missing RIFF
   在 DataTool.ConvertLogic.Sound.WwiseRIFFVorbis..ctor(Stream stream, String codebooksFile) 位置 F:\OWLib\DataTool\ConvertLogic\Sound.cs:行号 170
   在 DataTool.SaveLogic.Combo.ConvertSoundFile(Stream stream, Stream outputStream) 位置 F:\OWLib\DataTool\SaveLogic\Combo.cs:行号 702
System.Exception: missing RIFF
   在 DataTool.ConvertLogic.Sound.WwiseRIFFVorbis..ctor(Stream stream, String codebooksFile) 位置 F:\OWLib\DataTool\ConvertLogic\Sound.cs:行号 170
   在 DataTool.SaveLogic.Combo.ConvertSoundFile(Stream stream, Stream outputStream) 位置 F:\OWLib\DataTool\SaveLogic\Combo.cs:行号 702
        Done
[Core] Execution finished in 00:12:03.0112650 seconds

**Comment by DearVa** [comment]
It saved some of map files, about 1.06 GB in total, then it crashed and throw an exception.

**Comment by ZingBallyhoo** [comment]
It didn't crash, look at the end of the log. It just failed to convert 3 sounds.
