### ISSUE TITLE
Some portraits are black and white

### ISSUE THREAD

**Issue by komocode** [overtools/OWLib#77]
**Describe the bug**

**To Reproduce**
I used these commands to extract the portrait images.

> DataTool.exe D:\Blizzard\Overwatch\ extract-unlocks E:\Output "Reaper|icon=*"
> DataTool.exe D:\Blizzard\Overwatch\ extract-unlocks E:\Output "Tracer|icon=*"
> DataTool.exe D:\Blizzard\Overwatch\ extract-unlocks E:\Output "Mercy|icon=*"
> DataTool.exe D:\Blizzard\Overwatch\ extract-unlocks E:\Output "Hanzo|icon=*"
> DataTool.exe D:\Blizzard\Overwatch\ extract-unlocks E:\Output "Torbjörn|icon=*"
> DataTool.exe D:\Blizzard\Overwatch\ extract-unlocks E:\Output "Reinhardt|icon=*"
> DataTool.exe D:\Blizzard\Overwatch\ extract-unlocks E:\Output "Pharah|icon=*"
> DataTool.exe D:\Blizzard\Overwatch\ extract-unlocks E:\Output "Winston|icon=*"
> DataTool.exe D:\Blizzard\Overwatch\ extract-unlocks E:\Output "Widowmaker|icon=*"
> DataTool.exe D:\Blizzard\Overwatch\ extract-unlocks E:\Output "Bastion|icon=*"
> DataTool.exe D:\Blizzard\Overwatch\ extract-unlocks E:\Output "Symmetra|icon=*"
> DataTool.exe D:\Blizzard\Overwatch\ extract-unlocks E:\Output "Zenyatta|icon=*"
> DataTool.exe D:\Blizzard\Overwatch\ extract-unlocks E:\Output "Genji|icon=*"
> DataTool.exe D:\Blizzard\Overwatch\ extract-unlocks E:\Output "Roadhog|icon=*"
> DataTool.exe D:\Blizzard\Overwatch\ extract-unlocks E:\Output "McCree|icon=*"
> DataTool.exe D:\Blizzard\Overwatch\ extract-unlocks E:\Output "Junkrat|icon=*"
> DataTool.exe D:\Blizzard\Overwatch\ extract-unlocks E:\Output "Zarya|icon=*"
> DataTool.exe D:\Blizzard\Overwatch\ extract-unlocks E:\Output "Soldier|icon=*"
> DataTool.exe D:\Blizzard\Overwatch\ extract-unlocks E:\Output "Lúcio|icon=*"
> DataTool.exe D:\Blizzard\Overwatch\ extract-unlocks E:\Output "Va|icon=*"
> DataTool.exe D:\Blizzard\Overwatch\ extract-unlocks E:\Output "Mei|icon=*"
> DataTool.exe D:\Blizzard\Overwatch\ extract-unlocks E:\Output "Sombra|icon=*"
> DataTool.exe D:\Blizzard\Overwatch\ extract-unlocks E:\Output "Doomfist|icon=*"
> DataTool.exe D:\Blizzard\Overwatch\ extract-unlocks E:\Output "Ana|icon=*"
> DataTool.exe D:\Blizzard\Overwatch\ extract-unlocks E:\Output "Orisa|icon=*"
> DataTool.exe D:\Blizzard\Overwatch\ extract-unlocks E:\Output "Brigitte|icon=*"
> DataTool.exe D:\Blizzard\Overwatch\ extract-unlocks E:\Output "Moira|icon=*"
> DataTool.exe D:\Blizzard\Overwatch\ extract-unlocks E:\Output "Wrecking|icon=*"
> DataTool.exe D:\Blizzard\Overwatch\ extract-unlocks E:\Output "Ashe|icon=*"
> DataTool.exe D:\Blizzard\Overwatch\ extract-unlocks E:\Output "Baptiste|icon=*"
> DataTool.exe D:\Blizzard\Overwatch\ extract-unlocks E:\Output "Sigma|icon=*"

Some of the images are a black silhouette with a white background. Like Ashe and Sigma

> 

**Expected behavior**

Images should show the portrait of the character
**Logs**
If applicable, add logs to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Overwatch Version [e.g. 50125]
 - Overwatch Region [e.g. Americas]
 - Overwatch Language [e.g. English]
Windows 10
Overwatch 1.44.0.1.65575

**Additional context**

**Comment by ZingBallyhoo** [comment]
Newer portraits are multisurface textures. The second surface has the normal colour image. Use a viewer like IrfanView that can support it.

You do not need to specify every hero manually, you can use `*` e.g `*|icon=*` to get all player icons for all heroes (please note, I am not talking about hero portraits)
