### ISSUE TITLE
How do you even use it? The wiki tutorials suck and are not very descriptive, and have no experience codin gor programing. please help asap!

### ISSUE THREAD

**Issue by cutebubblegumpop** [overtools/OWLib#78]
Hey, um... how to hell do you even use this. I used to use the quickdatatool, but everyone gave up on that, and i was trying to find tutorials on the facepunch server, but it is taken down now. I seriously need help asap please.

There is no actual descriptive tutorial/ video tutorial on how the hell to use it, so i would love if you could help me out. Also please email me with any kind of help aswell cause i probably wont get a notification from here. thanks.

**Comment by Js41637** [comment]
Download the toolchain, the links to the builds are in the readme. run DataTool.exe in a command window, it shows you the help. Admitedly it's not very useful but, it's like most other command line tools.

The tutorial isn't that complex https://owdev.wiki/Tutorial/Extracting_with_DataTool

You can join the Discord if you want help on how to use the tools. https://discord.gg/XM93ZdB

**Comment by ZingBallyhoo** [comment]
resolved on discord
