### ISSUE TITLE
Could not load DLL 'librevorb.dll'

### ISSUE THREAD

**Issue by meleusi** [overtools/OWLib#89]
**Describe the bug**
command:

datatool -L=koKR -T=koKR c:\games\overwatch extract-hero-voice c:\extract\koKR 메르시

it says couldn't load 'librevorb.dll'

**Expected behavior**
extract KR Mercy Voice.

**Logs**

Processing data for 메르시 (Mercy)
        Saving Default
[Combo] Error converting sound: System.DllNotFoundException: DLL 'librevorb.dll'을(를) 로드할 수 없습니다. 지정된 모듈을 찾을 수 없습니다. (예외가 발생한 HRESULT: 0x8007007E) (Could not load DLL 'librevorb.dll'. Specified module not found (HRESULT: 0x8007007E with exception))
   위치(Location): RevorbStd.Native.revorb(REVORB_FILE& fi, REVORB_FILE& fo)
   위치(Location): RevorbStd.Revorb.Jiggle(Stream fi)
   위치(Location): DataTool.SaveLogic.Combo.ConvertSoundFile(Stream stream, Stream outputStream)[Combo] Error converting sound: System.DllNotFoundException: DLL 'librevorb.dll'을(를) 로드할 수 없습니다. 지정된 모듈을 찾을 수 없습니다. (예외가 발생한 HRESULT: 0x8007007E) (Could not load DLL 'librevorb.dll'. Specified module not found (HRESULT: 0x8007007E with exception))
   위치(Location): RevorbStd.Native.revorb(REVORB_FILE& fi, REVORB_FILE& fo)
   위치(Location): RevorbStd.Revorb.Jiggle(Stream fi)
   위치(Location): DataTool.SaveLogic.Combo.ConvertSoundFile(Stream stream, Stream outputStream)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 2004 64 Bit
 - Overwatch Version 1.51.1.0.72127
 - Overwatch Region koKR & enUS
 - Overwatch Language koKR & enUS

**Additional context**
Also TankView cannot convert sounds, models, etc
But can convert Strings. (Datatool & TankView)
librevorb.dll in folder.

After Extraction

![주석 2020-08-24 161942](https://user-images.githubusercontent.com/70131384/91015181-af73c600-e625-11ea-9b1b-b4efa63aa200.png)

**Comment by Js41637** [comment]
librevorb is bundled with the download, did you extract all the files in the zip properly?

https://ci.appveyor.com/project/yretenai/owlib/builds/34768745/artifacts

Download the tools and make sure you extract all the files.

**Comment by meleusi** [comment]
I said clearly that the librevorb.dll is in the folder.

![1](https://user-images.githubusercontent.com/70131384/91015959-fc0bd100-e626-11ea-9c6a-0e27a43bd495.png)

**Comment by Js41637** [comment]
i dunno, download and extract them again, it works fine for me using the same command, either you did it incorrectly or there is something weird with your Windows?
