### ISSUE TITLE
Export of UI sprites/icons

### ISSUE THREAD

**Issue by djurczak** [overtools/OWLib#9]
I wasn't sure how to contact you with this question so I hope you are fine with me opening a ticket here.

I have been trying to find a way to export the UI elements (e.g. the sprites that are used in the killfeed, scoreboard or HUD) from the game but have not yet found an obvious path to do that. Is there any easy way to get them through OverTool ?

cheers

**Comment by naomichan** [comment]
Not yet, it's on the wishlist though.

**Comment by djurczak** [comment]
Thanks for the quick response. Looking forward to that..

Guess I will have to figure out if there is a way to do that for now with CASCExplorer or something like that.

**Comment by Js41637** [comment]
You can do this pretty easy with CASCExplorer, just export all 004 and 04D folders to a directory, put TextureTool and CASCLib in the folder containing the `04D` and `004` folders and run

`TextureTool.exe ./dds r ./004 ./04D`

And it will convert every item, then go into the DDS folder when its done which will take a while and I think it's the 04D folder will have like 10,000 files but most are all the good stuff. The 004 has all the model textures which you're not interested in if you want UI stuff tho there is a _few_ things in there.

**Comment by Js41637** [comment]
Here's an example of mine of stuff that is exported, theres only actually 7000 but 4000 of them cant even be viewed and is mostly garbage
![image](https://cloud.githubusercontent.com/assets/6258213/26676182/1205ee56-470a-11e7-972f-4ee48e4758c6.png)

**Comment by djurczak** [comment]
Thanks for the hint @Js41637 

I tried to do that via CASCExplorer but failed. When I use the vanilla version directly from Github (https://github.com/WoW-Tools/CASCExplorer/releases) I can't seem to load any of the actual content:

![cascexplorer_1](https://cloud.githubusercontent.com/assets/12154/26682611/6932f59e-46e1-11e7-88bf-ed85ee168963.PNG)

Alternatively, if I follow the directions from the OWDev wikipage (https://owdev.wiki/Tutorial/Extracting) about extracting and copy CascLib.dll and ow.keys into the CASCExplorer directory I end up with an exception:

![cascexplorer_2](https://cloud.githubusercontent.com/assets/12154/26682711/b8c95f30-46e1-11e7-8be8-dd2a87d27df1.PNG)

I tried the last two or three builds of CASCExplorer but couldn't get it to extract anything. Anyway, I don't want to hijack this issue ticket even more with talk about an issue with CASCExplorer.

**Comment by naomichan** [comment]
https://ci.appveyor.com/api/buildjobs/9foep5kk3thpwp89/artifacts/dist%2FRelease%2FCascLib.dll

**Comment by djurczak** [comment]
@naomichan thanks so much. 

Just for my own sanity did I miss something somewhere and used an old version of that dll ?

**Comment by naomichan** [comment]
No, the wiki pages just are outdated.
