### ISSUE TITLE
voice lines in different languages

### ISSUE THREAD

**Issue by andrewnow123** [overtools/OWLib#92]
How do I import voice lines in different languages ?
The Wiki says how to import voice lines, but doesn't tell you how to import into different languages.
Please write an example of which command you need to write to import voice lines into different languages

**Comment by ZingBallyhoo** [comment]
`--L frFR --T frFr` for french. language codes are in the tool help

**Comment by andrewnow123** [comment]
Can you give an example or a link ? # #

**Comment by ZingBallyhoo** [comment]
just add `--L language --T language` to the end of any command

**Comment by andrewnow123** [comment]
@ZingBallyhoo Thank you!

**Comment by andrewnow123** [comment]
@ZingBallyhoo please give a link to the instruction.

**Comment by Js41637** [comment]
You need to do `--L=frFR --T=frFR`. There is no instructions apart from the help the tool logs if you don't enter an input.

**Comment by andrewnow123** [comment]
Thank you! @Js41637

**Comment by Js41637** [comment]
You can join the discord if you want more help, it's a lot easier to communicate about issues. There is a link in the readme at the top.

**Comment by andrewnow123** [comment]
@Js41637 Thank you!
